In [1]:
import sys
import os
import xarray as xr
import matplotlib.pyplot as plt
sys.path.append(os.path.join(os.environ['HOME'], 'Isca'))    # So can access functions in isca_tools which is in home/Isca directory
import isca_tools
import numpy as np

In [62]:
# Plot evolution of net flux and temperature to see how long it takes to spin up
def plot_spinup(ds_full, ds_ocean, ds_land, ax, albedo, tau):
    olr_sum = ds_full.olr.sum(dim = ['lon', 'lat'])
    short_wave_sum = ds_full.swdn_toa.sum(dim = ['lon', 'lat'])
    # Include surface albedo which reflects all SW radiation reaching it
    # SW radiation reaching it has been reduced by that absorbed in the atmosphere - non zero short wave optical depth.
    # There is no absorption on return trip from surface to space though hence just the one factor.
    net_flux = olr_sum - short_wave_sum*(1-albedo*np.exp(-tau))
    net_flux.plot.line(ax=ax, color='b')
    ax.set_ylabel('TOA Net Outgoing FLux / $Wm^{-2}$\nOLR - (1-$\\alpha e^{-\\tau})SW$', color='b')
    t_ocean = ds_ocean.t_surf.mean(dim = ['location']) - 273.15  # In Celsius
    t_land = ds_land.t_surf.mean(dim = ['location']) - 273.15  # In Celsius
    ax2 = ax.twinx()
    t_ocean.plot.line(ax=ax2, color='r', label='Ocean')
    t_land.plot.line(ax=ax2, color='r', linestyle=':', label='Land')
    ax2.set_ylabel('Surface Temperature / $°C$', color='r')
    ax2.legend()


In [2]:
# Load dataset across all months for each depth value
exp_name = 'play/min_max_output'
ds_max = isca_tools.load_dataset(exp_name+'/max')
ds_min = isca_tools.load_dataset(exp_name+'/min')
namelist = isca_tools.load_namelist(exp_name+'/max')  # Need this for albedo_value

In [5]:
ds_min.sel(lon=[240.125], lat=[40.3], method="nearest").t_surf.mean(dim=['lon','lat']).to_numpy()

array([281.7167 , 282.02655, 282.33777, 282.64917, 282.9316 ],
      dtype=float32)

In [6]:
ds_max.sel(lon=[240.125], lat=[40.3], method="nearest").t_surf.mean(dim=['lon','lat']).to_numpy()

array([281.58734, 281.87137, 282.1835 , 282.49597, 282.79446],
      dtype=float32)

In [3]:
ds_min.sel(lon=[240.125], lat=[40.3], method="nearest").t_surf.mean(dim=['lon','lat']).to_numpy()

array([281.28094, 281.18628, 281.1229 , 281.06073, 280.98593],
      dtype=float32)